name: RiseOfLands
version: '${project.version}'
main: me.sialim.riseoflands.RiseOfLands
api-version: '1.21'
author: bermei
depend: [PlaceholderAPI, Lands]
commands:
  religion:
    description: Manage your culture
    usage: /<command> <create|join|leave|delete> <culturename>
    aliases:
      - r
      - culture
      - cult
      - c