name: RiseOfLands
version: '${project.version}'
main: me.sialim.riseoflands.RiseOfLandsMain
api-version: '1.21'
author: bermei
depend: [PlaceholderAPI, Lands, AdvancedSeasons, Vault, LuckPerms]
commands:
  religion:
    description: Manage your culture
    usage: /<command> <create|join|leave|delete> <culturename>
    aliases:
      - r
      - culture
      - cult
      - c
  identity:
    description: Manage your identity
    usage: /<command> <create|label>
  setdate:
    usage: /setdate YYYY-MM-DD
  pause:
    usage: /pause
  resume:
    usage: /resume
  date:
    description: "Set date format or time format."
    usage: "/date format [format] or /date time [12|24]"
  temperature:
    description: "Set temperature preference."
    usage: "/temperature set [celsius|fahrenheit]"
  buildershop:
    description: "Opens the builder shop."
    usage: "/buildershop"